import { RecordingData } from '../types';

export function exportToAE(data: RecordingData) {
  const { compWidth, compHeight, duration, bodies, frames } = data;

  let jsx = `
// Generated by PhysicsToAE
app.beginUndoGroup("Physics Import");

var compName = "Physics Simulation";
var compWidth = ${compWidth};
var compHeight = ${compHeight};
var compDuration = ${duration / 1000};
var compFps = 60;

var comp = app.project.items.addComp(compName, compWidth, compHeight, 1, compDuration, compFps);
comp.openInViewer();

function hexToRgb(hex) {
    hex = hex.replace(/^#/, '');
    var bigint = parseInt(hex, 16);
    var r = (bigint >> 16) & 255;
    var g = (bigint >> 8) & 255;
    var b = bigint & 255;
    return [r/255, g/255, b/255];
}

var layers = {};
`;

  // Create layers
  Object.values(bodies).forEach((body) => {
    if (body.type === 'ground') {
      jsx += `
// Create Ground: ${body.label}
var shapeLayer_${body.id} = comp.layers.addShape();
shapeLayer_${body.id}.name = "${body.label}";
var shapeGroup_${body.id} = shapeLayer_${body.id}.property("ADBE Root Vectors Group");
var rect_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Shape - Rect");
rect_${body.id}.property("ADBE Vector Rect Size").setValue([${body.width}, ${body.height}]);
var fill_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Graphic - Fill");
fill_${body.id}.property("ADBE Vector Fill Color").setValue(hexToRgb("${body.color}"));
layers[${body.id}] = shapeLayer_${body.id};
`;
    } else if (body.type === 'box') {
      jsx += `
// Create Box: ${body.label}
var shapeLayer_${body.id} = comp.layers.addShape();
shapeLayer_${body.id}.name = "${body.label}";
var shapeGroup_${body.id} = shapeLayer_${body.id}.property("ADBE Root Vectors Group");
var rect_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Shape - Rect");
rect_${body.id}.property("ADBE Vector Rect Size").setValue([${body.width}, ${body.height}]);
var fill_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Graphic - Fill");
fill_${body.id}.property("ADBE Vector Fill Color").setValue(hexToRgb("${body.color}"));
layers[${body.id}] = shapeLayer_${body.id};
`;
    } else if (body.type === 'ball') {
      jsx += `
// Create Ball: ${body.label}
var shapeLayer_${body.id} = comp.layers.addShape();
shapeLayer_${body.id}.name = "${body.label}";
var shapeGroup_${body.id} = shapeLayer_${body.id}.property("ADBE Root Vectors Group");
var ellipse_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Shape - Ellipse");
ellipse_${body.id}.property("ADBE Vector Ellipse Size").setValue([${(body.radius || 0) * 2}, ${(body.radius || 0) * 2}]);
var fill_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Graphic - Fill");
fill_${body.id}.property("ADBE Vector Fill Color").setValue(hexToRgb("${body.color}"));
layers[${body.id}] = shapeLayer_${body.id};
`;
    } else if (body.type === 'text') {
      jsx += `
// Create Text: ${body.label}
var textLayer_${body.id} = comp.layers.addText("${body.textValue}");
textLayer_${body.id}.name = "${body.label}";
var textProp_${body.id} = textLayer_${body.id}.property("Source Text");
var textDoc_${body.id} = textProp_${body.id}.value;
textDoc_${body.id}.fontSize = ${body.fontSize};
textDoc_${body.id}.fillColor = hexToRgb("${body.color}");
textDoc_${body.id}.justification = ParagraphJustification.CENTER_JUSTIFY;
textProp_${body.id}.setValue(textDoc_${body.id});

// Fix anchor point to center
var sourceRect_${body.id} = textLayer_${body.id}.sourceRectAtTime(0, false);
textLayer_${body.id}.property("Anchor Point").setValue([
    sourceRect_${body.id}.left + sourceRect_${body.id}.width / 2,
    sourceRect_${body.id}.top + sourceRect_${body.id}.height / 2
]);
layers[${body.id}] = textLayer_${body.id};
`;
    } else if (body.type === 'svg') {
      jsx += `
// Create SVG Placeholder: ${body.label}
var shapeLayer_${body.id} = comp.layers.addShape();
shapeLayer_${body.id}.name = "${body.label} (Replace with SVG)";
var shapeGroup_${body.id} = shapeLayer_${body.id}.property("ADBE Root Vectors Group");
var rect_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Shape - Rect");
rect_${body.id}.property("ADBE Vector Rect Size").setValue([${body.width}, ${body.height}]);
var fill_${body.id} = shapeGroup_${body.id}.addProperty("ADBE Vector Graphic - Fill");
fill_${body.id}.property("ADBE Vector Fill Color").setValue(hexToRgb("${body.color}"));
fill_${body.id}.property("ADBE Vector Fill Opacity").setValue(50); // Placeholder opacity
layers[${body.id}] = shapeLayer_${body.id};
`;
    }
  });

  // Apply keyframes
  jsx += `\n// Apply Keyframes\n`;
  
  Object.values(bodies).forEach((body) => {
    if (body.type === 'ground') {
      // Set static position
      jsx += `layers[${body.id}].property("Position").setValue([${body.initialPos.x}, ${body.initialPos.y}]);\n`;
      return;
    }

    const times: number[] = [];
    const positions: string[] = [];
    const rotations: number[] = [];

    frames.forEach((frame) => {
      const bodyFrame = frame.bodies[body.id];
      if (bodyFrame) {
        times.push(frame.time / 1000); // Convert ms to seconds
        positions.push(`[${bodyFrame.x}, ${bodyFrame.y}]`);
        // Matter.js angle is in radians, AE rotation is in degrees
        rotations.push(bodyFrame.angle * (180 / Math.PI));
      }
    });

    if (times.length > 0) {
      jsx += `
var times_${body.id} = [${times.join(', ')}];
var positions_${body.id} = [${positions.join(', ')}];
var rotations_${body.id} = [${rotations.join(', ')}];

layers[${body.id}].property("Position").setValuesAtTimes(times_${body.id}, positions_${body.id});
layers[${body.id}].property("Rotation").setValuesAtTimes(times_${body.id}, rotations_${body.id});
`;
    }
  });

  jsx += `
app.endUndoGroup();
`;

  // Trigger download
  const blob = new Blob([jsx], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'physics_simulation.jsx';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
